### ISSUE TITLE
test.result can be falsy

### ISSUE THREAD

**Issue by mittinatten** [eratio08/vitest-teamcity-reporter#167]
Hi, and thanks for a very useful package.

We occasionally get an error in TeamCity from the reporter itself: 
```
TypeError: Cannot read properties of undefined (reading 'state')
      at /opt/buildagent/work/.../node_modules/vitest-teamcity-reporter/lib/printer.js:55:42
      at /opt/buildagent/work/.../node_modules/vitest-teamcity-reporter/lib/printer.js:25:83
      at Array.flatMap (<anonymous>)
      at Printer.handeUpdate (/opt/buildagent/work/.../node_modules/vitest-teamcity-reporter/lib/printer.js:25:22)
      at Array.forEach (<anonymous>)
      at Timeout._onTimeout (/opt/buildagent/work/.../node_modules/vitest-teamcity-reporter/lib/reporter.js:17:33)
      at listOnTimeout (node:internal/timers:564:17)
      at process.processTimers (node:internal/timers:507:7)
```
i.e. pointing to this line: https://github.com/eratio08/vitest-teamcity-reporter/blob/main/src/app/printer.ts#L72. It prints after the tests seemingly are finished, so I assume it fails in an `afterEach` or `afterAll`, and from the stack-trace it looks like a timeout. This is probably because we have a flaky test or flaky cleanup, but it's hard to tell where with this error message. 

Not sure what is the best solution, but at least `test.result` isn't always defined in the mentioned line. I am not familiar with reporter interface, but I would guess an undefined result can be interpreted as a failure.

**Comment by eratio08** [comment]
Thanks for reporting! I will try to take a look, but feel free to provide a PR for this.

**Comment by mittinatten** [comment]
I have done some further investigation, and it's not conclusive, but I think maybe the case we're seeing here is related to an [issue in vitest](https://github.com/vitest-dev/vitest/issues/2008) . I'm not sure, because after I added the `hanging-process` reporter, I haven't seen the issue from `vitest-teamcity-reporter` (which could indicate that the there's some relation between the two).

**Comment by a3mitskevich** [comment]
Hi. I opened a pull request with a potential fix for a related bug. But I not reproduce it on my device. 
@mittinatten can you provide some additional information about the test suit context where the bug is reproduced?

**Comment by mittinatten** [comment]
I'm afraid I can't give you a reproducible test case, it's been very sporadic. However, it seems to be related to an error with hanging-processes in Vite, as mentioned. If you have I/O-intensive tests (in my case tests that required compilation of a lot of svelte and typescript code) it's seem much more likely to happen. When I reduced the scope of some of my most flaky test I now see this error very rarely instead of 20-50% of the time.

**Comment by mittinatten** [comment]
Ironically I got a reproducible case just after I sent the last message :)
```ts
beforeAll(async () => {
  return new Promise((resolve) => setTimeout(resolve, 10000));
}, 100);
```

So I guess my initial suspicion about timeouts in `beforeAll` was correct, and it could possibly be that the compilation steps I mentioned above caused the same types of timeouts.

**Comment by a3mitskevich** [comment]
@mittinatten Thank you. After your code snipped, I found there was a problem and changed fix to another solution. 

The main problem then the suite failed the related tests not completed in Vitest. Now if the test has not resulted they get an error from the parent or file.

**Comment by eratio08** [comment]
@a3mitskevich sorry for taking so long will take a look at the pr now

**Comment by mittinatten** [comment]
This works perfectly. Thank you very much!
