### ISSUE TITLE
Support for vitests 1.x (without forcing the dependencies)

### ISSUE THREAD

**Issue by pjmolina** [eratio08/vitest-teamcity-reporter#216]
Hi:
The current version has:

```json
 "peerDependencies": {
...
    "vitest": ">=0.34.0"
  },
``` 

Which is good! 
However npm interpret it as `"vitest": ">=0.34.0 && < 1"`.

Could you change it to be more explicit to support vitests versions greater than 1? with something like:

```json
 "peerDependencies": {
...
    "vitest": ">=0.34.0 || >=1.0.0"
  },
```

**Comment by eratio08** [comment]
Thanks for your contribution! It's released
