### ISSUE TITLE
Teamcity doesn't recognise failed tests

### ISSUE THREAD

**Issue by MarcPaper** [eratio08/vitest-teamcity-reporter#38]
**Problem**:

Tests failing in vitest are not recognised as failed in Teamcity.

**Analysis**:

Information for failed tests printed by vitest-teamcity-reporter are not escaped as specified in the [Service Message Documentation](https://www.jetbrains.com/help/teamcity/service-messages.html).

**Proposed solution**:

Use the method `escape` from `printer.ts` to escape all arguments passed to `printTestFailed`

**Comment by MarcPaper** [comment]
Related pull request: https://github.com/eratio08/vitest-teamcity-reporter/pull/39

**Comment by eratio08** [comment]
resolved in https://github.com/eratio08/vitest-teamcity-reporter/pull/39
